name: tencent_cos_plus
description: A powerful tencent cos plugin, support bucket and object basic api.
version: 1.2.2
homepage: https://github.com/TryImpossible/flutter-plugins/tree/main/packages/tencent_cos_plus
repository: https://github.com/TryImpossible/flutter-plugins/tree/main/packages/tencent_cos_plus
issue_tracker: https://github.com/TryImpossible/flutter-plugins/issues

environment:
  sdk: ^3.8.1

dependencies:
  # https://pub.flutter-io.cn/packages/path
  path: ^1.9.1
  # https://pub.flutter-io.cn/packages/http
  http: ^1.4.0
  # https://pub.flutter-io.cn/packages/http_parser
  http_parser: ^4.1.2
  # https://pub.flutter-io.cn/packages/mime
  mime: ^2.0.0
  # https://pub.flutter-io.cn/packages/html
  html: ^0.15.6
  # https://pub.flutter-io.cn/packages/crypto
  crypto: ^3.0.6
  # https://pub.flutter-io.cn/packages/xml
  xml: ^6.6.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
