name: flutter_jsbridge_sdk
description: A lightweight jsbridge for sending messages between flutter and javascript in WebViews.
version: 1.0.2
homepage: https://github.com/TryImpossible/flutter-plugins/tree/main/packages/flutter_jsbridge_sdk
repository: https://github.com/TryImpossible/flutter-plugins/tree/main/packages/flutter_jsbridge_sdk
issue_tracker: https://github.com/TryImpossible/flutter-plugins/issues

environment:
  sdk: ^3.8.1

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
