name: flutter_iframe_webview
description: A WebView widget on web, provides a solution for WebView to interact with JS.
version: 1.0.0
homepage: https://github.com/TryImpossible/flutter-plugins/tree/main/packages/flutter_iframe_webview
repository: https://github.com/TryImpossible/flutter-plugins/tree/main/packages/flutter_iframe_webview
issue_tracker: https://github.com/TryImpossible/flutter-plugins/issues

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      web:
        pluginClass: WebWebViewPlatform
        fileName: webview_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  webview_flutter_platform_interface: ^2.0.0
  flutter_jsbridge_sdk: ^1.0.2

dev_dependencies:
  lints: ^5.0.0
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
